<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'config' => 'get1',
);

    protected function get1()
    {
        $object = new WooProductSets\System\Config(NULL);
        return $object;
    }

}
